"""empty message

Revision ID: 0f20fe85c174
Revises: 
Create Date: 2020-06-29 20:25:12.214178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f20fe85c174'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fsblog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fstitulo', sa.String(length=100), nullable=False),
    sa.Column('fsurl', sa.String(length=100), nullable=False),
    sa.Column('fsvideo', sa.String(length=1000), nullable=True),
    sa.Column('fsfoto', sa.String(length=1000), nullable=True),
    sa.Column('fsdescripcion', sa.String(length=100), nullable=False),
    sa.Column('fssubtitulo', sa.String(length=100), nullable=False),
    sa.Column('fscuerpo', sa.String(length=10000), nullable=False),
    sa.Column('fscode', sa.String(length=10000), nullable=True),
    sa.Column('fscreatedate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('icomblog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icomtitulo', sa.String(length=100), nullable=False),
    sa.Column('icomurl', sa.String(length=100), nullable=False),
    sa.Column('icomvideo', sa.String(length=1000), nullable=True),
    sa.Column('icomfoto', sa.String(length=1000), nullable=True),
    sa.Column('icomdescripcion', sa.String(length=100), nullable=False),
    sa.Column('icomsubtitulo', sa.String(length=100), nullable=False),
    sa.Column('icomcuerpo', sa.String(length=10000), nullable=False),
    sa.Column('icomcode', sa.String(length=10000), nullable=True),
    sa.Column('icomcreatedate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rolename', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rolename')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('avatar', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('createdate', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('icomblog')
    op.drop_table('fsblog')
    # ### end Alembic commands ###
